export { default as ProfileIcon } from "./profileIcon";
export { default as LampIcon } from "./lampIcon";
export { default as TalentIcon } from "./talentIcon";
export { default as CustomerIcon } from "./customerIcon";
export { default as RedCarpetRewardsIcon } from "./redCarpetRewardsIcon";
export { default as BusinessFormCouldBeBrand } from "./businessFormCouldBeBrand";
export { default as BusinessFormArrow } from "./businessFormArrow";
export { default as GoogleIcon } from "./google";
export { default as MasterCardIcon } from "./masterCard";
