import React from "react";

const LampIcon = ({
  size = 74,
  primaryColor = "#475867",
  secondaryColor = "#05ca97",
}) => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
      width={size}
      height={size}
    >
      <g id="Artwork">
        <circle
          cx="32.05"
          cy="30.65"
          r="14.75"
          fill="none"
          stroke={primaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M38.27,44.4v8.8a1.56,1.56,0,0,1-1.55,1.56H27.39a1.56,1.56,0,0,1-1.55-1.56V44.4"
          fill="none"
          stroke={primaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <line
          x1="30.54"
          y1="58.94"
          x2="33.65"
          y2="58.94"
          fill="none"
          stroke={primaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M42.35,34.16a10.65,10.65,0,0,1-.87,1.91"
          fill="none"
          stroke={primaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M32.05,19.78A10.88,10.88,0,0,1,42.93,30.65"
          fill="none"
          stroke={primaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <line
          x1="32"
          y1="5.06"
          x2="32"
          y2="9.64"
          fill="none"
          stroke={secondaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <line
          x1="13.9"
          y1="12.55"
          x2="17.14"
          y2="15.79"
          fill="none"
          stroke={secondaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <line
          x1="50.1"
          y1="48.75"
          x2="46.86"
          y2="45.52"
          fill="none"
          stroke={secondaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <line
          x1="6.4"
          y1="30.65"
          x2="10.98"
          y2="30.65"
          fill="none"
          stroke={secondaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <line
          x1="57.6"
          y1="30.65"
          x2="53.02"
          y2="30.65"
          fill="none"
          stroke={secondaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <line
          x1="13.9"
          y1="48.75"
          x2="17.14"
          y2="45.52"
          fill="none"
          stroke={secondaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <line
          x1="50.1"
          y1="12.55"
          x2="46.86"
          y2="15.79"
          fill="none"
          stroke={secondaryColor}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </g>
    </svg>
  );
};

export default LampIcon;
