export const artistsData = [
  {
    id: "1",
    name: "James Buckley",
    designation: "Singer · Curator",
    rating: 4.9,
    reviews: 1200,
    tags: ["Lo-fi", "Chill", "Focus"],
    price: 39,
    oldPrice: 100,
    eta: 48,
    slotsLeft: 2,
    image: "/images/artists/artist-1.jpg",
    username: "/buxtagram",
  },
  {
    id: "2",
    name: "Bofem",
    designation: "Tiktok Creator",
    reviews: 1200,
    tags: ["Lo-fi", "Chill", "Focus"],
    image: "/images/artists/artist-2.png",
    price: 65,
    eta: 48,
    slotsLeft: 2,
    rating: 4.99,
    username: "/bofem",
  },
  {
    id: "3",
    name: "Jen from Corporate",
    designation: "Prank Caller, Comedian, Actress Creator",
    image: "/images/artists/artist-3.jpg",
    price: 32,
    eta: 48,
    slotsLeft: 2,
    rating: 4.4,
    reviews: 1200,
    tags: ["Lo-fi", "Chill", "Focus"],
    username: "/w0ahhkate",
  },
  {
    id: "4",
    name: "Smooth Papi",
    designation: "Tiktok Creator",
    image: "/images/artists/artist-4.png",
    price: 61,
    eta: 48,
    slotsLeft: 2,
    rating: 4.97,
    tags: ["Lo-fi", "Chill", "Focus"],
    reviews: 1200,
    username: "/enochj_",
  },
  {
    id: "5",
    name: "SoYTiet",
    designation: "Count Master - Singer",
    image: "/images/artists/artist-5.jpg",
    price: 35,
    oldPrice: 100,
    eta: 48,
    slotsLeft: 2,
    rating: 4.86,
    reviews: 1200,
    username: "/soytiet",
    tags: ["Lo-fi", "Chill", "Focus"],
  },
  {
    id: "6",
    name: "Simon Kaggwa Njala",
    designation: "Journalist/Why are you gay sensation",
    image: "/images/artists/artist-6.png",
    price: 100,
    eta: 48,
    slotsLeft: 2,
    rating: 4.98,
    reviews: 1200,
    username: "/simonkaggwa",
    tags: ["Lo-fi", "Chill", "Focus"],
  },
  {
    id: "7",
    name: "Kori King",
    designation: "Rupauls Drag Race",
    image: "/images/artists/artist-7.png",
    price: 100,
    eta: 48,
    slotsLeft: 2,
    rating: 4.91,
    reviews: 1200,
    username: "/korikingg",
    tags: ["Lo-fi", "Chill", "Focus"],
  },
  {
    id: "8",
    name: "Jax Taylor",
    designation: "Bravo -Vanderpump Rules, The Valley",
    image: "/images/artists/artist-8.jpg",
    price: 159,
    eta: 48,
    slotsLeft: 2,
    rating: 4.94,
    reviews: 1200,
    username: "/mrjaxtaylor",
    tags: ["Lo-fi", "Chill", "Focus"],
  },
  {
    id: "9",
    name: "Big john  - the boshfather",
    designation: "Tiktok Creator",
    image: "/images/artists/artist-9.jpg",
    price: 39,
    eta: 48,
    slotsLeft: 2,
    rating: 4.99,
    reviews: 1200,
    username: "/bigjohn1",
    tags: ["Lo-fi", "Chill", "Focus"],
  },
  {
    id: "10",
    name: "cer spence / Spencer Goldman",
    designation: "comedian",
    image: "/images/artists/artist-10.jpg",
    price: 55,
    oldPrice: 110,
    eta: 48,
    slotsLeft: 2,
    rating: 4.94,
    reviews: 1200,
    username: "/cerspence",
    tags: ["Lo-fi", "Chill", "Focus"],
  },
  {
    id: "11",
    name: "cer spence / Spencer Goldman",
    designation: "comedian",
    image: "/images/artists/artist-10.jpg",
    price: 55,
    oldPrice: 110,
    eta: 48,
    slotsLeft: 2,
    rating: 4.94,
    reviews: 1200,
    username: "/cerspence",
    tags: ["Lo-fi", "Chill", "Focus"],
  },
];
