export const artistsData = [
  {
    id: "1",
    name: "Luna Waves",
    designation: "Indie Pop Singer · Songwriter",
    rating: 4.9,
    reviews: 2300,
    tags: ["Indie", "Pop", "Dreamy"],
    price: 49,
    oldPrice: 90,
    eta: 48,
    slotsLeft: 3,
    image: "https://placehold.co/400x400.png",
    username: "/lunawaves",
  },
  {
    id: "2",
    name: "DJ Stellar",
    designation: "Electronic Music Producer",
    rating: 4.95,
    reviews: 1800,
    tags: ["EDM", "House", "Dance"],
    price: 75,
    eta: 72,
    slotsLeft: 2,
    image: "https://placehold.co/400x400.png",
    username: "/djstellar",
  },
  {
    id: "3",
    name: "Hiro Tanaka",
    designation: "Lo-fi Beats Creator",
    rating: 4.88,
    reviews: 900,
    tags: ["Lo-fi", "Chill", "Focus"],
    price: 35,
    eta: 24,
    slotsLeft: 4,
    image: "https://placehold.co/400x400.png",
    username: "/hirobeats",
  },
  {
    id: "4",
    name: "Amara Soul",
    designation: "R&B Vocalist",
    rating: 4.97,
    reviews: 1200,
    tags: ["R&B", "Soul", "Jazz"],
    price: 65,
    oldPrice: 100,
    eta: 48,
    slotsLeft: 1,
    image: "https://placehold.co/400x400.png",
    username: "/amarasoul",
  },
  {
    id: "5",
    name: "The Echo Collective",
    designation: "Indie Rock Band",
    rating: 4.92,
    reviews: 2100,
    tags: ["Indie", "Rock", "Live"],
    price: 120,
    eta: 96,
    slotsLeft: 5,
    image: "https://placehold.co/400x400.png",
    username: "/echocollective",
  },
  {
    id: "6",
    name: "Zara Keys",
    designation: "Pianist · Composer",
    rating: 4.99,
    reviews: 1500,
    tags: ["Classical", "Piano", "Instrumental"],
    price: 100,
    eta: 72,
    slotsLeft: 2,
    image: "https://placehold.co/400x400.png",
    username: "/zarakeys",
  },
  {
    id: "7",
    name: "MC Blaze",
    designation: "Hip-Hop Artist",
    rating: 4.86,
    reviews: 950,
    tags: ["Hip-Hop", "Rap", "Beats"],
    price: 55,
    eta: 48,
    slotsLeft: 3,
    image: "https://placehold.co/400x400.png",
    username: "/mcblaze",
  },
  {
    id: "8",
    name: "Aurora Skye",
    designation: "Ambient Music Creator",
    rating: 4.91,
    reviews: 600,
    tags: ["Ambient", "Meditation", "Calm"],
    price: 42,
    eta: 24,
    slotsLeft: 2,
    image: "https://placehold.co/400x400.png",
    username: "/auroraskye",
  },
  {
    id: "9",
    name: "Rico Strings",
    designation: "Guitarist · Session Artist",
    rating: 4.89,
    reviews: 1100,
    tags: ["Acoustic", "Jazz", "Folk"],
    price: 70,
    eta: 48,
    slotsLeft: 2,
    image: "https://placehold.co/400x400.png",
    username: "/ricostrings",
  },
  {
    id: "10",
    name: "Velvet Vibes",
    designation: "Neo-Soul Band",
    rating: 4.94,
    reviews: 1400,
    tags: ["Neo-Soul", "Groove", "Live"],
    price: 130,
    oldPrice: 200,
    eta: 96,
    slotsLeft: 4,
    image: "https://placehold.co/400x400.png",
    username: "/velvetvibes",
  },
];
