export const categories = [
  { label: "House", value: "house" },
  { label: "Disco", value: "disco" },
  { label: "Trance", value: "trance" },
  { label: "Electro", value: "electro" },
  { label: "Techno", value: "techno" },
  { label: "Dubstep", value: "dubstep" },
  { label: "Big Room", value: "big-room" },
  { label: "Jungle", value: "jungle" },
  { label: "Drum and Bass", value: "drum-and-bass" },
  { label: "UK Garage", value: "uk-garage" },
  { label: "Indie Dance", value: "indie-dance" },
  { label: "Downtempo", value: "downtempo" },
  { label: "Breakbeat", value: "breakbeat" },
  { label: "Progressive House", value: "progressive-house" },
  { label: "Psytrance", value: "psytrance" },
  { label: "Dub", value: "dub" },
  { label: "Ambient", value: "ambient" },
  { label: "Bass", value: "bass" },
  { label: "Future Bass", value: "future-bass" },
  { label: "Afro House", value: "afro-house" },
  { label: "Trap Music", value: "trap-music" },
  { label: "Hip Hop", value: "hip-hop" },
  { label: "New Wave", value: "new-wave" },
  { label: "Tropical House", value: "tropical-house" },
  { label: "Dark Disco", value: "dark-disco" },
  { label: "Punk", value: "punk" },
  { label: "Pop", value: "pop" },
  { label: "Rock", value: "rock" },
  { label: "Minimal", value: "minimal" },
  { label: "Country", value: "country" },
  { label: "Eurodisco", value: "eurodisco" },
  { label: "Jazz", value: "jazz" },
  { label: "Industrial", value: "industrial" },
  { label: "Acid Techno", value: "acid-techno" },
  { label: "Funk", value: "funk" },
  { label: "Tech House", value: "tech-house" },
  { label: "Electro Swing", value: "electro-swing" },
  { label: "Ethnic Electronic", value: "ethnic-electronic" },
  { label: "Nu Jazz", value: "nu-jazz" },
  { label: "Dance-Pop", value: "dance-pop" },
  { label: "Nu Disco", value: "nu-disco" },
];
