export const VIBES = [
  { label: "Wedding", value: "wedding" },
  { label: "Chill", value: "chill" },
  { label: "Rave", value: "rave" },
  { label: "Day Party", value: "day-party" },
  { label: "Afters", value: "afters" },
  { label: "Poolside", value: "poolside" },
  { label: "Study/Focus", value: "study/focus" },
  { label: "Workout", value: "workout" },
  { label: "Road Trip", value: "road-trip" },
  { label: "Hiking", value: "hiking" },
  { label: "Sky Diving", value: "sky-diving" },
  { label: "Dark Lounge", value: "dark-lounge" },
  { label: "Meditating", value: "meditating" },
  { label: "Yoga Studio", value: "yoga-studio" },
  { label: "Smoking", value: "smoking" },
  { label: "Speakeasy", value: "speakeasy" },
  { label: "Hip Restaurant", value: "hip-restaurant" },
  { label: "Fireside", value: "fireside" },
  { label: "In my Pj’s", value: "in-my-pj’s" },
  { label: "Thunderstorm", value: "thunderstorm" },
  { label: "Festival", value: "festival" },
  { label: "In a Hammock", value: "in-a-hammock" },
  { label: "Palmtrees", value: "palmtrees" },
  { label: "Tropical", value: "tropical" },
  { label: "Nice Restaurant", value: "nice-restaurant" },
  { label: "Roller Rink", value: "roller-rink" },
  { label: "Warehouse", value: "warehouse" },
  { label: "Industrial", value: "industrial" },
];
