import { ClientProviders } from "@/provider/ClientProviders";
import type { Metadata } from "next";
import { Bricolage_Grotesque, Geist } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Artylst",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${bricolageGrotesque.variable} bg-base-900 antialiased bg-gradient-to-br from-brand-1/30 via-base-900 to-brand-5/30`}
        suppressHydrationWarning={true}
      >
        <div className="fixed inset-0 -z-10 bg-grid opacity-[.18]"></div>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
