import { ClientProviders } from "@/provider/ClientProviders";
import type { Metadata } from "next";
import "./globals.css";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";

export const metadata: Metadata = {
  title: "ARTYLST",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`bg-base-900 antialiased bg-gradient-to-br from-brand-1/30 via-base-900 to-brand-5/30`}
      >
        <div className="fixed inset-0 -z-10 bg-grid opacity-[.18]"></div>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
